name: sync posts

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  repository_dispatch:
    types: [sync_event]
jobs:
  blog-cicd:
    name: sync Hexo blog 
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
    - name: Checkout codes
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: sync yueque
      run: |
        npm install yuque-hexo -g
        YUQUE_TOKEN=${{secrets.YUQUE_TOKEN}} yuque-hexo sync

    - name: Commit & push changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add .
        git commit -m "GitHub Actions Auto Sync Post at $(date +'%Y-%m-%d %H:%M:%S')"
        git push
